random_seed: 47
wandb:
  offline: False
  project: "lung-cancer-detection"
artifacts:
  data:
    name: lidc-idri-raw
    version: v1
    type: dataset
    description: "Zipped dataset of all chest CT scans, masks and nodule volumes in npy format, including scan and nodule metadata. Updated with new volume size for nodules."
  train:
    name: lidc-train
    version: v1
    type: dataset
    description: "List of patient IDs included in the training set"
  valid:
    name: lidc-valid
    version: v1
    type: dataset
    description: "List of patient IDs included in the validation set"
  class_model:
    name: nodule-classification-model
    version: v0
    type: model
    description: "Basic DenseNet for classifying lung nodules regarding their malignancy"
  seg_model:
    name: nodule-segmentation-model
    version: v0
    type: model
    description: "Basic UNet for segmenting lung nodules in chest CTs"
data:
  data_dir: ../data/full/processed/
  split_dir: ../data/full/splits/
  cache_dir: ../data/full/cache
  sample: False
  batch_size: 32
  val_split: 0.2
  min_anns: 1
  aug_prob: 0.1
seg_model:
  dimensions: 3
  in_channels: 1
  out_channels: 2
  features:
    - 32
    - 32
    - 64
    - 128
    - 256
    - 32
  dropout: 0.0
  lr: 0.0001
  norm:
    - instance
    - affine: True
class_model:
  num_classes: 2
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  lr: 0.00001
  dropout: 0.0
experiment:
  max_epochs: 100
  max_time:
    hours: 12
  auto_lr_find: True
  gpus: 1
  auto_select_gpus: True
  auto_scale_batch_size: False
